In [34]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

- CRIM — Bölge başına kişi başına suç oranı
- ZN — 25.000 fit kareyi aşan arsalar için ayrılmış konut arazisinin oranı
- INDUS — Bölge başına perakende dışı ticari alan oranı
- CHAS — Charles Nehri kukla değişkeni (bölge nehir sınırına değiyorsa 1, aksi halde 0)
- NOX — Nitrik oksit konsantrasyonu (10 milyonda bir parça)
- RM — Konut başına ortalama oda sayısı
- AGE — 1940 öncesinde inşa edilmiş, sahibi tarafından kullanılan konutların oranı
- DIS — Boston'daki beş istihdam merkezine ağırlıklı mesafe
- RAD — Çevre yollarına erişilebilirlik endeksi
- TAX — 10.000 dolar başına tam değerli mülk vergisi oranı
- PTRATIO — Bölge başına öğrenci-öğretmen oranı
- B — 1000(Bk - 0.63)², Bk bölgedeki siyahi nüfusun oranı
- LSTAT — Düşük gelirli nüfusun yüzdesi
- MEDV — Sahibi tarafından kullanılan konutların medyan değeri (1000 dolar cinsinden)

In [35]:
# Sütun isimlerini manuel veriyoruz , çünkü ilk satır data ve bu veri setinde columns eklenmemiş.Sklearn
# hazır kütüphanesinden de indiremiyoruz.
columns = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 
           'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']

df = pd.read_csv('housing.csv', header=None, names=columns, sep='\s+')
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [36]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [37]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')

In [38]:
df.shape

(506, 14)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64
 4   nox      506 non-null    float64
 5   rm       506 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64
 9   tax      506 non-null    float64
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [40]:
df.isnull().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

In [41]:
df.duplicated().sum()

np.int64(0)

In [44]:
def aykiri_deger_raporu(df):
    rapor = []
    
    for col in df.columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        
        alt_sinir = Q1 - 1.5 * IQR
        ust_sinir = Q3 + 1.5 * IQR
        
        aykirilar = df[(df[col] < alt_sinir) | (df[col] > ust_sinir)][col]
        
        rapor.append({
            'Sütun'        : col,
            'Q1'           : round(Q1, 2),
            'Q3'           : round(Q3, 2),
            'IQR'          : round(IQR, 2),
            'Alt Sınır'    : round(alt_sinir, 2),
            'Üst Sınır'    : round(ust_sinir, 2),
            'Aykırı Sayısı': len(aykirilar),
            'Aykırı %'     : round(len(aykirilar) / len(df) * 100, 2)
        })
    
    return pd.DataFrame(rapor)
aykiri_deger_raporu(df)

,Sütun,Q1,Q3,IQR,Alt Sınır,Üst Sınır,Aykırı Sayısı,Aykırı %
0,crim,0.08,3.68,3.60,-5.31,9.07,66,13.04
1,zn,0.00,12.50,12.50,-18.75,31.25,68,13.44
2,indus,5.19,18.10,12.91,-14.18,37.47,0,0.00
3,chas,0.00,0.00,0.00,0.00,0.00,35,6.92
4,nox,0.45,0.62,0.18,0.19,0.89,0,0.00
5,rm,5.89,6.62,0.74,4.78,7.73,30,5.93
6,age,45.02,94.07,49.05,-28.55,167.65,0,0.00
7,dis,2.10,5.19,3.09,-2.53,9.82,5,0.99
8,rad,4.00,24.00,20.00,-26.00,54.00,0,0.00
9,tax,279.00,666.00,387.00,-301.50,1246.50,0,0.00
10,ptratio,17.40,20.20,2.80,13.20,24.40,15,2.96
11,b,375.38,396.22,20.85,344.11,427.50,77,15.22
12,lstat,6.95,16.96,10.01,-8.06,31.96,7,1.38
13,medv,17.02,25.00,7.98,5.06,36.96,40,7.91

In [47]:
# chas binary değişken olduğu için listede yok
cols_to_cap = ['crim', 'zn', 'rm', 'dis', 'ptratio', 'b', 'lstat', 'medv']

for col in cols_to_cap:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    alt = Q1 - 1.5 * IQR
    ust = Q3 + 1.5 * IQR
    df[col] = df[col].clip(lower=alt, upper=ust)

# Kontrol et
rapor_sonra = aykiri_deger_raporu(df)
print(rapor_sonra[['Sütun', 'Aykırı Sayısı', 'Aykırı %']].to_string(index=False))

  Sütun  Aykırı Sayısı  Aykırı %
   crim              0      0.00
     zn              0      0.00
  indus              0      0.00
   chas             35      6.92
    nox              0      0.00
     rm              0      0.00
    age              0      0.00
    dis              0      0.00
    rad              0      0.00
    tax              0      0.00
ptratio              0      0.00
      b              0      0.00
  lstat              0      0.00
   medv              0      0.00