In [51]:
import pandas as pd

We use the pd.get_dummies() function to apply one-hot encoding to the DataFrame df. This function automatically detects the categorical column(s) and creates new binary columns for each unique category. The dtype=int argument ensures the encoding is done with 1 and 0 instead of the default Booleans

In [59]:
data = {'Color' : ['Red' ,'Green' , 'Blue', 'Red']}
df = pd.DataFrame(data)
# Applying one-hot encoding
# This funct firstl sort the list , after assign
df_encoded = pd.get_dummies(df,dtype=int)
print(df_encoded)

   Color_Blue  Color_Green  Color_Red
0           0            0          1
1           0            1          0
2           1            0          0
3           0            0          1

For more flexibility and control over the encoding process, Scikit-learn offers the OneHotEncoder class. This class provides advanced options, such as handling unknown categories and fitting the encoder to the training data.

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
enc = OneHotEncoder(handle_unknown='ignore')

X= [['Red'] ,['Blue'], ['Green'] ]
enc.fit(X)
result = enc.transform([['Blue']]).toarray()
print(result)

In [76]:
from sklearn.feature_extraction import FeatureHasher
import pandas as pd 

data = {'Color': ['Red', 'Green', 'Blue', 'Red', 'Yellow']}
df = pd.DataFrame(data)

hasher = FeatureHasher(n_features=3, input_type='string')

# ✅ Her rengi liste içinde veriyoruz
hashed_features = hasher.transform([[color] for color in df['Color']])

hashed_df = pd.DataFrame(
    hashed_features.toarray(), 
    columns=['Feature1', 'Feature2', 'Feature3']
)

print("Hashed Features Df:")
print(hashed_df)

Hashed Features Df:
   Feature1  Feature2  Feature3
0       0.0       0.0       1.0
1       0.0       1.0       0.0
2      -1.0       0.0       0.0
3       0.0       0.0       1.0
4       0.0      -1.0       0.0

Biz yukarıda yaptığımız şey:
Biz aslında şunu bulduk:
Renkleri modelin anlayabileceği sayısal forma çevirdik!
Yani amacımız insan için anlam üretmek değil, model için sayısal girdi üretmek!
n_features ≥ unique kategori sayısı olursa
collision riski azalır!
Feature Hashing matematiksel olarak tek adımda çalıştığı için her zaman daha hızlıdır. Ama 3k unique kategoride hız farkı çok dramatik olmaz. Asıl hız farkı 100k+ unique kategoride kendini gösterir!

In [77]:
import numpy as np
from scipy.sparse import csr_matrix

# Define a dense matrix
dense_matrix = np.array([[0, 0, 3], [0, 5, 0], [0, 0, 0]])
# Convert the dense matrix to the sparse matrix
sparse_matrix = csr_matrix(dense_matrix)
# Print the sparse matrix
print(sparse_matrix)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 3)>
  Coords	Values
  (0, 2)	3
  (1, 1)	5

In [60]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [ ]:
# Creating the encode
enc = OneHotEncoder(handle_unknown='ignore')
# ignore kullandığımız için bilinmeyen kategoriler tamamen 
# 0 vektörü alır. Bu bazen bilgi kaybına yol açabilir. 
# Ama production ortamında model çökmemesi için genellikle 
# tercih edilir.
# Sample data
X= [['Red'] ,['Blue'], ['Green'] ]
# Fitting the encoder to the data
enc.fit(X)
# Transforming new data
result = enc.transform([['Blue']]).toarray()
print(result)

[[1. 0. 0.]]

enc.transform() sonucu direkt olarak sparse matrix döndürür:(0, 1)  1.0   ← Sparse matrix! İnsan gözüyle okunamaz 😵

**Sparse matrix nedir?**

Büyük veri setlerinde çoğu değer 0'dır:
```
10.000 kategori varsa:
[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...]
# Sadece 1 tane 1 var, geri kalan 9999 tane 0!
# Bunları saklamak çok yer kaplar!
Sparse matrix sadece 0 olmayan değerleri saklar → Çok daha az bellek kullanır! ✅
.toarray() ile bunu normal okunabilir diziye çeviriyoruz:

In [18]:
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder

In [19]:
data = {
    'Employee id': [10, 20, 15, 25, 30],
    'Gender': ['M', 'F', 'F', 'M', 'F'],
    'Remarks': ['Good', 'Nice', 'Good', 'Great', 'Nice']
}
print("Orginal Employee Df")
df = pd.DataFrame(data)
df

Orginal Employee Df

   Employee id Gender Remarks
0           10      M    Good
1           20      F    Nice
2           15      F    Good
3           25      M   Great
4           30      F    Nice

In [20]:
df_pandas_encoded = pd.get_dummies(df , columns=['Gender' , 'Remarks'])
print(f"One-Hot Encoded Data using Pandas:\n{df_pandas_encoded}\n")

One-Hot Encoded Data using Pandas:
   Employee id  Gender_F  Gender_M  Remarks_Good  Remarks_Great  Remarks_Nice
0           10     False      True          True          False         False
1           20      True     False         False          False          True
2           15      True     False          True          False         False
3           25     False      True         False           True         False
4           30      True     False         False          False          True

In [22]:
df_pandas_encoded = pd.get_dummies(df , columns=['Gender' , 'Remarks'] , drop_first=True)
print(f"One-Hot Encoded Data using Pandas:\n{df_pandas_encoded}\n")

One-Hot Encoded Data using Pandas:
   Employee id  Gender_M  Remarks_Great  Remarks_Nice
0           10      True          False         False
1           20     False          False          True
2           15     False          False         False
3           25      True           True         False
4           30     False          False          True

In [ ]:
df_pandas_encoded = pd.get_dummies(df , columns=['Gender' , 'Remarks'] , drop_first=True)
print(f"One-Hot Encoded Data using Pandas:\n{df_pandas_encoded}\n")

In [25]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder , StandardScaler

data = {
    'Employee id': [10, 20, 15, 25, 30],
    'Gender': ['M', 'F', 'F', 'M', 'F'],
    'Remarks': ['Good', 'Nice', 'Good', 'Great', 'Nice']
}

df = pd.DataFrame(data)
print(f"Original Employee Data:\n{df}\n")
# Use pd.get_dummies() to one-hot encode the categorical columns
df_pandas_encoded = pd.get_dummies(df, columns=['Gender', 'Remarks'], drop_first=True)
print(f"One-Hot Encoded Data using Pandas:\n{df_pandas_encoded}\n")

encoder = OneHotEncoder(sparse_output=False)
categorical_columns = ['Gender', 'Remarks']
one_hot_encoded = encoder.fit_transform(df[categorical_columns])

one_hot_df = pd.DataFrame(one_hot_encoded, 
                          columns=encoder.get_feature_names_out(categorical_columns))

df_sklearn_encoded = pd.concat([df.drop(categorical_columns, axis=1), one_hot_df], axis=1)

print(f"One-Hot Encoded Data using Scikit-Learn:\n{df_sklearn_encoded}\n")

Original Employee Data:
   Employee id Gender Remarks
0           10      M    Good
1           20      F    Nice
2           15      F    Good
3           25      M   Great
4           30      F    Nice

One-Hot Encoded Data using Pandas:
   Employee id  Gender_M  Remarks_Great  Remarks_Nice
0           10      True          False         False
1           20     False          False          True
2           15     False          False         False
3           25      True           True         False
4           30     False          False          True

One-Hot Encoded Data using Scikit-Learn:
   Employee id  Gender_F  Gender_M  Remarks_Good  Remarks_Great  Remarks_Nice
0           10       0.0       1.0           1.0            0.0           0.0
1           20       1.0       0.0           0.0            0.0           1.0
2           15       1.0       0.0           1.0            0.0           0.0
3           25       0.0       1.0           0.0            1.0           0.0
4           30       1.0       0.0           0.0            0.0           1.0

In [26]:
#  k fold cross-validation

In [27]:
from sklearn.model_selection import cross_val_score, KFold
from sklearn.svm import SVC
from sklearn.datasets import load_iris

In [28]:
iris = load_iris()
X, y = iris.data, iris.target

In [29]:
svm_classifier = SVC(kernel='linear')

In [30]:
num_folds = 5
kf = KFold(n_splits=num_folds, shuffle=True, random_state=42)

In [ ]:
# We use cross_val_score() to automatically split data, 
# train and evaluate the model across all folds. 
# It returns the accuracy for each fold

In [31]:
cross_val_results = cross_val_score(svm_classifier, X, y, cv=kf)

In [32]:
print("Cross-Validation Results (Accuracy):")
for i, result in enumerate(cross_val_results, 1):
    print(f"  Fold {i}: {result * 100:.2f}%")
    
print(f'Mean Accuracy: {cross_val_results.mean()* 100:.2f}%')

Cross-Validation Results (Accuracy):
  Fold 1: 100.00%
  Fold 2: 100.00%
  Fold 3: 96.67%
  Fold 4: 93.33%
  Fold 5: 96.67%
Mean Accuracy: 97.33%

NEW

In [33]:
# Importing Libraries 
import pandas as pd
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Loading Data
X, y = load_wine(return_X_y=True)

# Train/Test Split : random_state = 49
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=49)

rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

accuracy_score(y_test, y_pred)
print('Accuracy score for random_state = 49 : ' + str(accuracy_score(y_test, y_pred)))

Accuracy score for random_state = 49 : 0.9722222222222222

In [34]:
# Train/Test Split  : random_state = 1234
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=1234)

rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

accuracy_score(y_test, y_pred)
print('Accuracy score for random_state = 1234 : ' + str(accuracy_score(y_test, y_pred)))

Accuracy score for random_state = 1234 : 0.9444444444444444

Yukarıdaki kod çıktısında farklı bölünmeler(random_state’ler) için accuracy skorlarının değiştiğini dolayısıyla tek bir veri seti üzerinden modelin performansını değerlendirmenin yanıltıcı olabileceğini gözlemledik. Amacımız mümkün olduğunca objektif ve doğru bir şekilde modelimizin performansını değerlendirmek olduğundan train-test split yaklaşımı bu noktada eksik kalıyor ve bu sebeple cross-validation yöntemine ihtiyaç duyuluyor.

NOT : K değerinin gözlem sayısına uygun olarak seçilmemesi modelin performansının yanlış değerlendirilmesine sebep olabilir. K değerini seçmek için kesin bir kural olamamakla birlikte genellikle 5 ya da 10 olarak ayarlanabilir.

In [ ]:

# K-fold split
X, y = load_wine(return_X_y=True)

folds = KFold(n_splits = 5, shuffle = True, random_state = 35)
scores = []

for n_fold, (train_index, valid_index) in enumerate(folds.split(X,y)):
    print('\n Fold '+ str(n_fold+1 ) + 
          ' \n\n train ids :' +  str(train_index) +
          ' \n\n test ids :' +  str(valid_index))
    
    X_train, X_valid = X[train_index], X[valid_index]
    y_train, y_valid = y[train_index], y[valid_index]
    
    rf_model.fit(X_train, y_train)
    y_pred = rf_model.predict(X_test)
    
    acc_score = accuracy_score(y_test, y_pred)
    scores.append(acc_score)
    print('\n Accuracy score for Fold ' +str(n_fold+1) + ' --> ' + str(acc_score)+'\n')

    
print(scores)
print('Avg. accuracy score :' + str(np.mean(scores)))

 Fold 1

 train ids :[  0   1   2   4   5   6   8   9  11  12  13  15  16  18  19  20  23  24
  26  27  28  29  30  31  32  33  34  35  36  37  39  40  41  42  44  45
  47  48  50  51  52  53  54  55  56  57  58  59  60  61  62  63  65  66
  67  68  69  70  71  72  73  75  76  78  79  81  82  83  85  86  87  88
  90  91  93  94  97  98  99 100 101 102 103 105 106 107 108 110 111 112
 114 115 116 118 119 120 121 122 123 125 126 127 128 129 131 133 134 135
 136 137 138 139 140 141 143 144 146 147 149 150 153 154 155 157 158 159
 160 161 163 164 165 166 167 168 169 171 172 173 174 175 176 177]

 validation ids :[  3   7  10  14  17  21  22  25  38  43  46  49  64  74  77  80  84  89
  92  95  96 104 109 113 117 124 130 132 142 145 148 151 152 156 162 170]

 Accuracy score for Fold 1 --> 1.0


 Fold 2

 train ids :[  0   1   2   3   4   5   7   8   9  10  11  14  15  16  17  18  19  20
  21  22  24  25  26  28  29  32  33  34  35  36  37  38  39  41  42  43
  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  62
  63  64  65  66  67  70  71  73  74  75  76  77  78  80  82  84  85  89
  90  92  93  94  95  96  97  99 100 101 102 103 104 106 108 109 110 111
 113 114 115 117 118 119 122 123 124 125 126 127 128 130 131 132 133 134
 135 136 137 139 141 142 144 145 148 149 150 151 152 153 154 155 156 157
 158 159 161 162 163 164 165 167 168 169 170 172 173 174 175 176]

 validation ids :[  6  12  13  23  27  30  31  40  61  68  69  72  79  81  83  86  87  88
  91  98 105 107 112 116 120 121 129 138 140 143 146 147 160 166 171 177]

 Accuracy score for Fold 2 --> 0.9444444444444444


 Fold 3

 train ids :[  0   1   2   3   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  25  26  27  28  29  30  31  33  36  38  39  40  41
  43  44  45  46  48  49  54  55  56  57  59  60  61  62  63  64  66  67
  68  69  71  72  74  76  77  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  95  96  98  99 100 104 105 107 108 109 110 111 112 113
 114 116 117 118 119 120 121 122 124 125 126 129 130 131 132 133 134 136
 137 138 139 140 142 143 144 145 146 147 148 149 150 151 152 154 156 157
 160 162 163 164 165 166 167 168 169 170 171 172 173 175 176 177]

 validation ids :[  4  24  32  34  35  37  42  47  50  51  52  53  58  65  70  73  75  78
  94  97 101 102 103 106 115 123 127 128 135 141 153 155 158 159 161 174]

 Accuracy score for Fold 3 --> 1.0


 Fold 4

 train ids :[  1   3   4   6   7   9  10  12  13  14  15  17  18  19  21  22  23  24
  25  27  29  30  31  32  33  34  35  37  38  39  40  42  43  44  45  46
  47  49  50  51  52  53  55  56  57  58  59  61  64  65  67  68  69  70
  72  73  74  75  76  77  78  79  80  81  83  84  85  86  87  88  89  90
  91  92  94  95  96  97  98 101 102 103 104 105 106 107 109 111 112 113
 115 116 117 120 121 122 123 124 125 126 127 128 129 130 131 132 134 135
 138 139 140 141 142 143 144 145 146 147 148 149 151 152 153 155 156 158
 159 160 161 162 164 165 166 167 169 170 171 172 173 174 175 176 177]

 validation ids :[  0   2   5   8  11  16  20  26  28  36  41  48  54  60  62  63  66  71
  82  93  99 100 108 110 114 118 119 133 136 137 150 154 157 163 168]

 Accuracy score for Fold 4 --> 1.0


 Fold 5

 train ids :[  0   2   3   4   5   6   7   8  10  11  12  13  14  16  17  20  21  22
  23  24  25  26  27  28  30  31  32  34  35  36  37  38  40  41  42  43
  46  47  48  49  50  51  52  53  54  58  60  61  62  63  64  65  66  68
  69  70  71  72  73  74  75  77  78  79  80  81  82  83  84  86  87  88
  89  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 112 113 114 115 116 117 118 119 120 121 123 124 127 128 129
 130 132 133 135 136 137 138 140 141 142 143 145 146 147 148 150 151 152
 153 154 155 156 157 158 159 160 161 162 163 166 168 170 171 174 177]

 validation ids :[  1   9  15  18  19  29  33  39  44  45  55  56  57  59  67  76  85  90
 111 122 125 126 131 134 139 144 149 164 165 167 169 172 173 175 176]

 Accuracy score for Fold 5 --> 1.0

[1.0, 0.9444444444444444, 1.0, 1.0, 1.0]
Avg. accuracy score :0.9888888888888889

Şimdi de sklearn kütüphanesinin model_selection modülünden import ettigimiz cross_val_score fonksiyonunu kullanarak “wine” veri setini 10 parçaya bölüp ortalama accuracy değerini hesaplayalım.

In [36]:
# Kfold Split with cross_val_score
from sklearn.model_selection import cross_val_score
X, y = load_wine(return_X_y=True)
scores = cross_val_score(rf_model, X, y, cv=10)
scores.mean()

np.float64(0.9833333333333334)

Stratified K-Fold Cross Validation

In [37]:
from statistics import mean, stdev
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold
from sklearn import linear_model
from sklearn import datasets

In [38]:
cancer = datasets.load_breast_cancer()

x = cancer.data
y = cancer.target

In [39]:
# MinMaxScaler(): scales features to a range between 0 and 1
# fit_transform(x): fits scaler on data and applies transformation
scaler = preprocessing.MinMaxScaler()
x_scaled = scaler.fit_transform(x)

In [40]:
# Now we will use logistic regression
lr = linear_model.LogisticRegression()

skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
lst_accu_stratified = []
# lst_accu_stratified: empty list to store accuracy scores

In [41]:
for train_index, test_index in skf.split(x, y):
	x_train_fold, x_test_fold = x_scaled[train_index], x_scaled[test_index]
	y_train_fold, y_test_fold = y[train_index], y[test_index]
	lr.fit(x_train_fold, y_train_fold)
	lst_accu_stratified.append(lr.score(x_test_fold, y_test_fold))

In [42]:
print('List of possible accuracy:', lst_accu_stratified)
print('\nMaximum Accuracy That can be obtained from this model is:',
	max(lst_accu_stratified)*100, '%')
print('\nMinimum Accuracy:',
	min(lst_accu_stratified)*100, '%')
print('\nOverall Accuracy:',
	mean(lst_accu_stratified)*100, '%')
print('\nStandard Deviation is:', stdev(lst_accu_stratified))

List of possible accuracy: [0.9298245614035088, 0.9649122807017544, 0.9824561403508771, 1.0, 0.9649122807017544, 0.9649122807017544, 0.9824561403508771, 0.9473684210526315, 0.9473684210526315, 0.9821428571428571]

Maximum Accuracy That can be obtained from this model is: 100.0 %

Minimum Accuracy: 92.98245614035088 %

Overall Accuracy: 96.66353383458647 %

Standard Deviation is: 0.02097789213195869

Here we can see that we got a overall accuracy of 96.6% and standard deviation of 0.02 which means our model is working fine.

By using Stratified K-Fold Cross Validation we can ensure that our machine learning model is evaluated fairly and consistently leading to more accurate predictions and better real-world performance

Implementation of K-Fold Cross Validation
Here’s a Python example of how to implement K-Fold Cross Validation using the scikit-learn library:

In [43]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import numpy as np

data = load_iris()
X, y = data.data, data.target  

# K-Fold Cross Validation
k = 5  
kf = KFold(n_splits=k, shuffle=True, random_state=42)

# Initialize the RandomForestClassifier model
model = RandomForestClassifier(random_state=42)

# Perform Cross Validation
scores = cross_val_score(model, X, y, cv=kf, scoring='accuracy')

print(f"Accuracy for each fold: {scores}")

average_accuracy = np.mean(scores) 
print(f"Average Accuracy: {average_accuracy:.2f}")

Accuracy for each fold: [1.         0.96666667 0.93333333 0.93333333 0.96666667]
Average Accuracy: 0.96

In [47]:
from sklearn import datasets
import pandas as pd

iris = datasets.load_iris()
data = pd.DataFrame(iris.get('data'), columns=[
    'sepal length', 'petal length', 'sepal width', 'sepal width'])
data.head()

   sepal length  petal length  sepal width  sepal width
0           5.1           3.5          1.4          0.2
1           4.9           3.0          1.4          0.2
2           4.7           3.2          1.3          0.2
3           4.6           3.1          1.5          0.2
4           5.0           3.6          1.4          0.2

Now let us perform a standard scaling on the sepal width column. Scaling in general means converting the column to a common number scale, Standard scaling in particular converts the column of interest by transforming it to a range of numbers with mean = 0 and standard deviation = 1.

In [48]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    data.iloc[:, :-1], data['sepal width'],
  test_size=0.33, random_state=42)

The fit() Method
The fit function computes the formulation to transform the column based on Standard scaling but doesn't apply the actual transformation. The computation is stored as a fit object. The fit method doesn't return anything.

In [49]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(data['sepal width'])

StandardScaler()

The transform() Method
The transform method takes advantage of the fit object in the fit() method and applies the actual transformation onto the column. So, fit() and transform() is a two-step process that completes the transformation in the second step. Here, Unlike the fit() method the transform method returns the actually transformed array.

In [50]:
scaler.transform(data['sepal width'])

array([[-1.34022653e+00, -1.31544430e+00],
       [-1.34022653e+00, -1.31544430e+00],
       [-1.39706395e+00, -1.31544430e+00],
       [-1.28338910e+00, -1.31544430e+00],
       [-1.34022653e+00, -1.31544430e+00],
       [-1.16971425e+00, -1.05217993e+00],
       [-1.34022653e+00, -1.18381211e+00],
       [-1.28338910e+00, -1.31544430e+00],
       [-1.34022653e+00, -1.31544430e+00],
       [-1.28338910e+00, -1.44707648e+00],
       [-1.28338910e+00, -1.31544430e+00],
       [-1.22655167e+00, -1.31544430e+00],
       [-1.34022653e+00, -1.44707648e+00],
       [-1.51073881e+00, -1.44707648e+00],
       [-1.45390138e+00, -1.31544430e+00],
       [-1.28338910e+00, -1.05217993e+00],
       [-1.39706395e+00, -1.05217993e+00],
       [-1.34022653e+00, -1.18381211e+00],
       [-1.16971425e+00, -1.18381211e+00],
       [-1.28338910e+00, -1.18381211e+00],
       [-1.16971425e+00, -1.31544430e+00],
       [-1.28338910e+00, -1.05217993e+00],
       [-1.56757623e+00, -1.31544430e+00],
       [-1.16971425e+00, -9.20547742e-01],
       [-1.05603939e+00, -1.31544430e+00],
       [-1.22655167e+00, -1.31544430e+00],
       [-1.22655167e+00, -1.05217993e+00],
       [-1.28338910e+00, -1.31544430e+00],
       [-1.34022653e+00, -1.31544430e+00],
       [-1.22655167e+00, -1.31544430e+00],
       [-1.22655167e+00, -1.31544430e+00],
       [-1.28338910e+00, -1.05217993e+00],
       [-1.28338910e+00, -1.44707648e+00],
       [-1.34022653e+00, -1.31544430e+00],
       [-1.28338910e+00, -1.31544430e+00],
       [-1.45390138e+00, -1.31544430e+00],
       [-1.39706395e+00, -1.31544430e+00],
       [-1.34022653e+00, -1.44707648e+00],
       [-1.39706395e+00, -1.31544430e+00],
       [-1.28338910e+00, -1.31544430e+00],
       [-1.39706395e+00, -1.18381211e+00],
       [-1.39706395e+00, -1.18381211e+00],
       [-1.39706395e+00, -1.31544430e+00],
       [-1.22655167e+00, -7.88915558e-01],
       [-1.05603939e+00, -1.05217993e+00],
       [-1.34022653e+00, -1.18381211e+00],
       [-1.22655167e+00, -1.31544430e+00],
       [-1.34022653e+00, -1.31544430e+00],
       [-1.28338910e+00, -1.31544430e+00],
       [-1.34022653e+00, -1.31544430e+00],
       [ 5.35408562e-01,  2.64141916e-01],
       [ 4.21733708e-01,  3.95774101e-01],
       [ 6.49083415e-01,  3.95774101e-01],
       [ 1.37546573e-01,  1.32509732e-01],
       [ 4.78571135e-01,  3.95774101e-01],
       [ 4.21733708e-01,  1.32509732e-01],
       [ 5.35408562e-01,  5.27406285e-01],
       [-2.60315415e-01, -2.62386821e-01],
       [ 4.78571135e-01,  1.32509732e-01],
       [ 8.07091462e-02,  2.64141916e-01],
       [-1.46640561e-01, -2.62386821e-01],
       [ 2.51221427e-01,  3.95774101e-01],
       [ 1.37546573e-01, -2.62386821e-01],
       [ 5.35408562e-01,  2.64141916e-01],
       [-8.98031345e-02,  1.32509732e-01],
       [ 3.64896281e-01,  2.64141916e-01],
       [ 4.21733708e-01,  3.95774101e-01],
       [ 1.94384000e-01, -2.62386821e-01],
       [ 4.21733708e-01,  3.95774101e-01],
       [ 8.07091462e-02, -1.30754636e-01],
       [ 5.92245988e-01,  7.90670654e-01],
       [ 1.37546573e-01,  1.32509732e-01],
       [ 6.49083415e-01,  3.95774101e-01],
       [ 5.35408562e-01,  8.77547895e-04],
       [ 3.08058854e-01,  1.32509732e-01],
       [ 3.64896281e-01,  2.64141916e-01],
       [ 5.92245988e-01,  2.64141916e-01],
       [ 7.05920842e-01,  6.59038469e-01],
       [ 4.21733708e-01,  3.95774101e-01],
       [-1.46640561e-01, -2.62386821e-01],
       [ 2.38717193e-02, -1.30754636e-01],
       [-3.29657076e-02, -2.62386821e-01],
       [ 8.07091462e-02,  8.77547895e-04],
       [ 7.62758269e-01,  5.27406285e-01],
       [ 4.21733708e-01,  3.95774101e-01],
       [ 4.21733708e-01,  5.27406285e-01],
       [ 5.35408562e-01,  3.95774101e-01],
       [ 3.64896281e-01,  1.32509732e-01],
       [ 1.94384000e-01,  1.32509732e-01],
       [ 1.37546573e-01,  1.32509732e-01],
       [ 3.64896281e-01,  8.77547895e-04],
       [ 4.78571135e-01,  2.64141916e-01],
       [ 1.37546573e-01,  8.77547895e-04],
       [-2.60315415e-01, -2.62386821e-01],
       [ 2.51221427e-01,  1.32509732e-01],
       [ 2.51221427e-01,  8.77547895e-04],
       [ 2.51221427e-01,  1.32509732e-01],
       [ 3.08058854e-01,  1.32509732e-01],
       [-4.30827696e-01, -1.30754636e-01],
       [ 1.94384000e-01,  1.32509732e-01],
       [ 1.27429511e+00,  1.71209594e+00],
       [ 7.62758269e-01,  9.22302838e-01],
       [ 1.21745768e+00,  1.18556721e+00],
       [ 1.04694540e+00,  7.90670654e-01],
       [ 1.16062026e+00,  1.31719939e+00],
       [ 1.61531967e+00,  1.18556721e+00],
       [ 4.21733708e-01,  6.59038469e-01],
       [ 1.44480739e+00,  7.90670654e-01],
       [ 1.16062026e+00,  7.90670654e-01],
       [ 1.33113254e+00,  1.71209594e+00],
       [ 7.62758269e-01,  1.05393502e+00],
       [ 8.76433123e-01,  9.22302838e-01],
       [ 9.90107977e-01,  1.18556721e+00],
       [ 7.05920842e-01,  1.05393502e+00],
       [ 7.62758269e-01,  1.58046376e+00],
       [ 8.76433123e-01,  1.44883158e+00],
       [ 9.90107977e-01,  7.90670654e-01],
       [ 1.67215710e+00,  1.31719939e+00],
       [ 1.78583195e+00,  1.44883158e+00],
       [ 7.05920842e-01,  3.95774101e-01],
       [ 1.10378283e+00,  1.44883158e+00],
       [ 6.49083415e-01,  1.05393502e+00],
       [ 1.67215710e+00,  1.05393502e+00],
       [ 6.49083415e-01,  7.90670654e-01],
       [ 1.10378283e+00,  1.18556721e+00],
       [ 1.27429511e+00,  7.90670654e-01],
       [ 5.92245988e-01,  7.90670654e-01],
       [ 6.49083415e-01,  7.90670654e-01],
       [ 1.04694540e+00,  1.18556721e+00],
       [ 1.16062026e+00,  5.27406285e-01],
       [ 1.33113254e+00,  9.22302838e-01],
       [ 1.50164482e+00,  1.05393502e+00],
       [ 1.04694540e+00,  1.31719939e+00],
       [ 7.62758269e-01,  3.95774101e-01],
       [ 1.04694540e+00,  2.64141916e-01],
       [ 1.33113254e+00,  1.44883158e+00],
       [ 1.04694540e+00,  1.58046376e+00],
       [ 9.90107977e-01,  7.90670654e-01],
       [ 5.92245988e-01,  7.90670654e-01],
       [ 9.33270550e-01,  1.18556721e+00],
       [ 1.04694540e+00,  1.58046376e+00],
       [ 7.62758269e-01,  1.44883158e+00],
       [ 7.62758269e-01,  9.22302838e-01],
       [ 1.21745768e+00,  1.44883158e+00],
       [ 1.10378283e+00,  1.71209594e+00],
       [ 8.19595696e-01,  1.44883158e+00],
       [ 7.05920842e-01,  9.22302838e-01],
       [ 8.19595696e-01,  1.05393502e+00],
       [ 9.33270550e-01,  1.44883158e+00],
       [ 7.62758269e-01,  7.90670654e-01]])

we cannot use the fit() method on the test dataset, because it will be the wrong approach as it could introduce bias to the testing dataset.